### ISSUE TITLE
Output emails are not always converted to lowercase

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#17]
In loading the Terravision data just now and doing a back-to-back with the old and new email extractors, I noticed slightly different results:

1. Old tool: 2,075,625 emails
2. New tool: 2,075,606 emails

Diffing both output files, it looks like one of the differences is that output email addresses aren't always lower-cased. I can't see a pattern for why this is so haven't been able to write a failing test for it. Instead, here's a screen cap of just part of the output with the original email extractor on the left and the current version of this tool on the right:

![image](https://user-images.githubusercontent.com/273244/233832138-8dba1857-d9f5-4921-a940-dfc75c140d84.png)

**Comment by GStefanowich** [comment]
This is easily changeable if lowercased emails are what you're looking for. I had changed it so that instead of calling `ToLower()` on every Regex match, that it instead uses a case-insensitive collection for gathering addresses.

Could either `.ToLower` on all matches again, or add it to the final Write method

**Comment by troyhunt** [comment]
Ah, I see now, that's within the test itself which it why the one checking email addresses are lower-cased always passes 🙂

How about moving that upstream into one of the methods that actually pulls the addresses out? I think there's still something different with the parsing compared to my old app, but at least a diff will make more sense once it's not full of minor case variations.

**Comment by GStefanowich** [comment]
I've added onto my PR #18 a call to lowercase before writing to output

    addresses.Select(address => address.ToLowerInvariant())
        .OrderBy(address => address, StringComparer.OrdinalIgnoreCase)

It'll lowercase it before sorting and then printing, not that the order really matters since you added the StringComparer

**Comment by KonajuGames** [comment]
With #18 merged, this is likely addressed.

**Comment by troyhunt** [comment]
Yep, seems to be, thanks everyone.
