### ISSUE TITLE
Handle email addresses encapsulated in double quotes

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#36]
Found another fairly major processing glitch there's now tests for in https://github.com/HaveIBeenPwned/EmailAddressExtractor/commit/84ee6089600eea82fd98ded17ec5501bec5ce22a. By running this app back to back with my oldie, I'm getting a good sense of how well the result sets align.

FWIW, I'm currently running it against this data set 😲 https://twitter.com/troyhunt/status/1651140792701059072

Lot of stuff like this:

`a:6:{s:5:\"email\";s:23:\"test@example.com\";s:8:\"password\";s:8:\"an`

**Comment by hiteshbedre** [comment]
Picking this up🚀

**Comment by troyhunt** [comment]
Perfect!
