### ISSUE TITLE
"Length cannot be less than zero" exception

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#54]
This is a really vague issue I'm raising here but I'm on a plane with a battery about to die so just reporting it as seen. Trying to run the latest app against a .sql file and it's throwing the following exception:

```
Found 1 files:
- .sql   1 files: 55.0 Gb
Extracting...
An error occurred while reading 'D:\Temp\file.sql': Length cannot be less than zero. (Parameter 'length')
Extraction time: 566ms
Addresses extracted: 148
Read lines total: 150
Read lines rate: 261/s
```

Any thoughts on where this is? We're hitting an edge case somewhere I suspect, line 151 is just a blank line. Here it is with 2 lines either side of it:

```
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `authorCrawls`
```

**Comment by GStefanowich** [comment]
Finally cracked the cause of this, will work on a fix
