### ISSUE TITLE
Domains should not be able to end with a period

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#65]
I just added a failing test for this (DomainEndingInPeriodIsInvalid) after finding some junk that had made its way through.

**Comment by KonajuGames** [comment]
A trailing period in a domain is valid. It represents the root hierarchy, and is usually assumed and not printed.

**Comment by troyhunt** [comment]
Is that the case for either a publicly addressable domain accessed over HTTP or the domain part of an email address? Happy to be proven wrong, but I don't think there's a single website address that has a period immediately after the TLD, is there?

**Comment by troyhunt** [comment]
Yeah, thought that might be the case. The decision we keep running into with this project is strict adherence to RFCs versus filtering out junk. If I was to look at the occurrences of periods at the end of domains in everything from domain searches to breach parsing to people signing up to notifications, I bet 100% of them will be parsing or user input errors rather than compliance with an RFC edge case! I'm also of the view that if you _could_ legitimately put a period at the end of say, an address, you'd be blocked in so many places you'd quickly stop doing that!

**Comment by KonajuGames** [comment]
That is a valid view, and related to the other issues where emails may start with { or /, but in real life the users impacted by a data breach will never have that. I would be in favour of stripping them per how we use them on the internet today rather than strict RFC compliance.

**Comment by troyhunt** [comment]
Yep, still an issue. In fact, this is our only failing test right now: https://github.com/HaveIBeenPwned/EmailAddressExtractor/blob/7bf5312f5600cda5e4c746c6ece4c4168fbbbef3/test/LegacyTests.cs#L168

**Comment by Johno-ACSLive** [comment]
Interesting, OK I'll investigate further.

**Comment by Johno-ACSLive** [comment]
The extractor was stripping the trailing period and if the other checks were passed we are left with presumably a valid email address. I would also be in favour of this unless you've seen examples where the other checks allow invalid email addresses through.

I've created a PR which invalidates email addresses with a trailing period.

**Comment by troyhunt** [comment]
I think this works perfectly for now, I can't see any other places it would cause issues, certainly all the tests pass successfully. Thanks!
