### ISSUE TITLE
An alias cannot be longer than 64 chars

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#66]
I just had an import fail because there's a 64 char max on the alias column and a breach had a bunch of junky records in it. There's now a failing test for this in https://github.com/HaveIBeenPwned/EmailAddressExtractor/commit/e8f9aa72fa185fa1f618f4b82eeb3862e601c49b, let's fix it!

**Comment by zikato** [comment]
I had trouble finding the failing test. Do you mean this commit 4b1d7738e4ada943caa5c4a946f5a67f15958917?

**Comment by troyhunt** [comment]
You're right, I screwed up the commit reference. This has now been implemented by @GStefanowich, but I'm not adverse to you having a go at doing it in the regex instead if you'd like.
