### ISSUE TITLE
Extracting addresses from a directory path should include subfolders

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#71]
At present, if the path is a directory then all files within that directory are scanned but none below it are. The entire directory tree beneath the starting point should be scanned.

**Comment by GStefanowich** [comment]
C'mon read your own docs man

> `-- recursive`
> Enable recursive mode for directories, which will search child directories

**Comment by troyhunt** [comment]
LOL, this is what happens when I try to process breaches while on holidays 🤣
